name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Authorising User ğŸ‘¨ğŸ»â€ğŸ’»
        run: echo "Hello World"
      - name: Auth User ğŸ–¥ï¸
        run: echo "Authorising User"
      - name: Verifying OTP
        run: echo "Verifying your OTP"
      - name: multiple Jobs
        run: |
               echo "First output"
               echo "Second output"
            
    
